Some further cleanups, making for slightly more robust glibc build rules.

diff --git a/contrib/Makefile b/contrib/Makefile
--- a/contrib/Makefile
+++ b/contrib/Makefile
@@ -34,36 +34,65 @@ OS_ID := $(shell case "$(target)" in \
 (*) echo "Target triple not yet supported: $(target)" 1>&2 ;; \
 esac)
 ifeq ($(OS_ID),debian)
+    os_family := debianlike
+else
+ifeq ($(OS_ID),ubuntu)
+    os_family := debianlike
+else
+    os_family := $(OS_ID)
+endif
+endif
 
+$(info OS_ID is $(OS_ID))
+$(info os_family is $(os_family))
+ifeq ($(os_family),debianlike)
+
+# we only use GLIBC_PKGSTR if GLIBC_SRC_DIR is not set
 GLIBC_PKGSTR := $(shell \
    binpkg="$$( dpkg -S $$(readlink -f $$(ls -1 /lib/x86_64*-linux-gnu/libc.so* | head -n1 ) ) | tr -s '[:blank:]' '\t' | cut -f1 | sed 's/:$$//')"; \
    dpkg-query --showformat='$${Package}=$${Version}\n' -W "$$binpkg" | sort | uniq )
 $(info GLIBC_PKGSTR is $(GLIBC_PKGSTR))
+LIBC_RULES_MK := $(shell case "$(GLIBC_PKGSTR)" in \
+ (*2.19) echo glibc-2.1x-debian.mk;;\
+ (*2.2*) echo glibc-2.2x-debian.mk;;\
+esac)
+
+ifeq ($(LIBC_RULES_MK),)
+$(error Did not recognise package/version: $(GLIBC_PKGSTR))
+endif
 
 # HACK: have to grab and unpack the package before we know its src dirname
-GLIBC_SRC_DIR := $(shell apt-get source "$(GLIBC_PKGSTR)" 1>&2 && \
+GLIBC_SRC_DIR ?= $(shell apt-get source "$(GLIBC_PKGSTR)" 1>&2 && \
                  find -maxdepth 1 -mindepth 1 -type d | xargs ls -1dt | head -n1 )
 LIBC_SRC_DIR := $(GLIBC_SRC_DIR)
+libc_src_dir := $(LIBC_SRC_DIR)
+
+ifeq ($(LIBC_SRC_DIR),)
+$(error Could not get libc source dir for package string $(GLIBC_PKGSTR) / source dir $(GLIBC_SRC_DIR))
+endif
 
 # HACK -- use change-prone knowledge of the build process here
 # HACK: please remove arch-specific strings here
 LIBC_BUILD_DIR := $(LIBC_SRC_DIR)/build-tree
 libc_build_dir := $(LIBC_BUILD_DIR)
 $(info libc_build_dir is $(libc_build_dir))
-$(LIBC_BUILD_DIR)/amd64-libc/elf: $(LIBC_BUILD_DIR)/amd64-libc/config.status
-	cd $(LIBC_SRC_DIR) && dpkg-buildpackage --no-sign -nc -rfakeroot
 
 .PHONY: build
-build: $(LIBC_BUILD_DIR)/amd64-libc/elf
+build: $(LIBC_BUILD_DIR)/amd64-libc/elf/ld.so
 
-config.mk:
+$(LIBC_BUILD_DIR)/amd64-libc/elf/ld.so: $(LIBC_SRC_DIR)
+	cd $(LIBC_SRC_DIR) && dpkg-buildpackage --no-sign -nc -rfakeroot
+
+config.mk: | build
 	(/bin/echo 'RTLD_OBJ_DIR := $(realpath $(libc_build_dir))/amd64-libc/elf'; \
 	 /bin/echo 'OS_ID := $(OS_ID)'; \
 	 /bin/echo 'LIBC_SRC_DIR := $(realpath $(LIBC_SRC_DIR))'; \
 	 /bin/echo 'PKG_VER := $(notdir $(LIBC_SRC_DIR))'; \
+	 /bin/echo 'LIBC_RULES_MK := $(realpath $(LIBC_RULES_MK))'; \
 	 ) \
 | sed '/^\\$$/ d' | sed 's/ *$$//' > "$@" || rm -f "$@"
-else
+
+else # the non-Debian-like case
 
 #    libcfile="$$(basename $$(readlink -f $$(ls -1 /lib/x86_64*-linux-gnu/libc.so* | head -n1 ) ) )"; \
 #    case "$$libcfile" in \
@@ -78,16 +107,18 @@ $(info LIBC_SRC_DIR is $(libc_src_dir))
 LIBC_BUILD_DIR := $(shell case "$(target)" in \
 (x86_64*-linux-gnu) \
     . /etc/os-release && case "$$ID" in \
-    (debian) \
+    (debian|ubuntu) \
         case "$(libc_src_dir)" in \
             (glibc-*) echo "$(libc_src_dir)"/build;; \
             (eglibc-*) echo "$(libc_src_dir)"/libc/build;; \
+            (*) echo "Error: no known libc build dir for $$ID (srcdir: $(libc_src_dir))" 1>&2;; \
         esac ;; \
     (*) echo "OS ID not yet supported: $$ID" 1>&2 ;; \
     esac;; \
 (*) echo "Target triple not yet supported: $(target)" 1>&2 ;; \
 esac)
 
+# default *also* includes extracting that
 default: extract
 
 endif
